### ISSUE TITLE
touchpad can work on macOS，cannot work on Windows.

### ISSUE THREAD

**Issue by LuxferreX** [postkevone/razer-blade-stealth-13-oc#1]
Touchpad can work on macOS，cannot work on Windows.
Already put ssdt-xosi.aml into ACPI folder and patch--rename _osi to xosi,but ssdt-i2c.aml&ssdt-tpxx.aml cause the issue on Windows.
But when I choose the“Windows Boot Manager” in BIOS，touchpad can work perfectly.
So I think maybe ssdt-i2c.aml or ssdt-tpxx.aml don't seem compatible.

**Comment by postkevone** [comment]
In this configuration there are is an ACPI patch that renames all the _STA methods in the TPD0 of all I2C devices, so I do not recommend to use OC to boot Windows as we cannot completely disable those patches.
You could add conditions to SSDT-I2C and SSDT-TPXX to behave like the original methods under Windows, but I think using a different bootloader such as reFind would be a better solution overall: https://github.com/dortania/Hackintosh-Mini-Guides/blob/master/refind.md.

If you still want to use OC you can also try this solution (SSDT-TPAD), however I do not recommend it: https://github.com/KatLantyss/Razer-Blade-Stealth-13-IceLake-Hackintosh?tab=readme-ov-file#specific-patch.

**Comment by postkevone** [comment]
I am going to close this issue as this is a problem related to the bootloader and not the configuration itself.

**Comment by LuxferreX** [comment]
> In this configuration there are is an ACPI patch that renames all the _STA methods in the TPD0 of all I2C devices, so I do not recommend to use OC to boot Windows as we cannot completely disable those patches. You could add conditions to SSDT-I2C and SSDT-TPXX to behave like the original methods under Windows, but I think using a different bootloader such as reFind would be a better solution overall: https://github.com/dortania/Hackintosh-Mini-Guides/blob/master/refind.md.
> 
> If you still want to use OC you can also try this solution (SSDT-TPAD), however I do not recommend it: https://github.com/KatLantyss/Razer-Blade-Stealth-13-IceLake-Hackintosh?tab=readme-ov-file#specific-patch.

ok，thx very much，you are really a nice guy.
