### ISSUE TITLE
unlocked bios cannot work

### ISSUE THREAD

**Issue by LuxferreX** [postkevone/razer-blade-stealth-13-oc#3]
Hi，I have flashed the mod bios in my device（same model)
My laptop boot normal,but I cannot open the bios settings（black screen）
So how can I open the bios settings？
Thx very much！
![1](https://github.com/postkevone/razer-blade-stealth-13-oc/assets/30519088/4773a536-23bb-42b8-813d-2955829e31cc)
![2](https://github.com/postkevone/razer-blade-stealth-13-oc/assets/30519088/9d6cdd2e-e550-41f2-b836-5552ac22d2fd)

**Comment by LuxferreX** [comment]
I have a try to connect a monitor or a TV，nothing happen.
😀
Also，I have try to remove the CMOS battery，nothing changed.

**Comment by postkevone** [comment]
That message pops up because you have Secure Boot enabled.
You should be able to enter the BIOS settings by pressing Ok and then disable it.
I recommend however to do you own modifications on your BIOS instead of flashing mine, just to be sure that works correctly.

**Comment by LuxferreX** [comment]
OK, I wiil try later，Thx😀

**Comment by postkevone** [comment]
I will close this as this seems solved.
