### ISSUE TITLE
how did you remove bios? or did you use SOP8 clip? thank you so much

### ISSUE THREAD

**Issue by abodypa9** [postkevone/razer-blade-stealth-13-oc#4]
how did you remove bios? or did you use SOP8 clip? thank you so much

**Comment by postkevone** [comment]
I used a programmer to modify the BIOS, here I wrote more information about how I did it: https://github.com/postkevone/razer-blade-stealth-13-oc/tree/main/BIOS#modding-the-bios

**Comment by abodypa9** [comment]
Yes, bro , I know, but did you remove the chip itself using hot air...or did you use clip?
![51U2V2tPFyL _AC_SL1000_](https://github.com/postkevone/razer-blade-stealth-13-oc/assets/86721202/8765797a-6162-4f16-97d1-75681aaa3512)

**Comment by postkevone** [comment]
I did not remove it, I used the clip while having the laptop connected to the power adaptor (without it the chip was not recognized).

**Comment by abodypa9** [comment]
Thank you, my CH341A  is on the way, I will find out later, sorry for disturbing you my friend

**Comment by postkevone** [comment]
No problem, make sure to use a programmer that supports 3.3V because the standard black version of CH341A did not work for me.

**Comment by abodypa9** [comment]
I used the black CH341A a year and a half ago and it was working for me.. but two weeks ago I used it. Unfortunately, it burned the BIOS chip and I was forced to change the BIOS chip. Then I tried it again and it did not work and was not read. That is why I order version 1.6 to determine the voltage. 3v   im sorry Last question  Did you use this piece with it , right?
![AT2ZMUA](https://github.com/postkevone/razer-blade-stealth-13-oc/assets/86721202/5ee8801d-5d95-4087-ab45-2ee9ab844762)

**Comment by postkevone** [comment]
Yes I used that piece. Always make sure to check the pin numbers before connecting.

**Comment by abodypa9** [comment]
I got it! Is this installation correct? Or I put it the other way around Thanks
![WhatsApp Image 2024-04-05 at 3 56 20 PM](https://github.com/postkevone/razer-blade-stealth-13-oc/assets/86721202/a9d60c38-f853-4930-91fd-e1ad8826c399)

**Comment by abodypa9** [comment]
every time i try its tell me " IC not responding "

**Comment by abodypa9** [comment]
Anyone coming from the future and having this problem "IC not responding" I already solved it, I had a lot of usb connected to the other computer, I think the problem was coming from the bluetooth adapter when I removed it, everything worked + you don't really need to turn on the power adapter in the laptop

**Comment by postkevone** [comment]
Closing this as solved, thanks for the instructions.
