### ISSUE TITLE
Mod bios doesn't work properly

### ISSUE THREAD

**Issue by dimka4996** [postkevone/razer-blade-stealth-13-oc#5]
I flashed a modified BIOS using the CH341A programmer, but when I try to enter the BIOS setup, I just get a black screen. When I revert to the original BIOS, I can access the BIOS menu without any issues. I tried to follow the guide for modifying the BIOS, but I don't understand where to find AMITSE and the separate setup data in our BIOS, as the guide suggests.

**Comment by dimka4996** [comment]
[modbios.zip](https://github.com/user-attachments/files/17192778/modbios.zip)
I made my own BIOS mod

**Comment by postkevone** [comment]
You may have a different BIOS file based on your region, that is why I always suggest to make your own modifications instead of flashing dumped BIOS files on the the internet.

As for the AMITSE and the separate setup data, they are a little hard to find but they should be included, please look more carefully.

**Comment by dimka4996** [comment]
> You may have a different BIOS file based on your region, that is why I always suggest to make your own modifications instead of flashing dumped BIOS files on the the internet.
> 
> As for the AMITSE and the separate setup data, they are a little hard to find but they should be included, please look more carefully.

I already modded it and attached here, look closely, but I'm still can't run MacOS and debug it properly, can you share config.plist file?

**Comment by postkevone** [comment]
you can find my EFI folder here #2

**Comment by dimka4996** [comment]
> you can find my EFI folder here #2

Contact me on Telegram; I’ve set up the configuration more or less now—sleep and wake work on the first try, hibernation, and more. You can update the repositories.

@onx_dmytro

**Comment by postkevone** [comment]
I would rather not be contacted privately about this. If you have settings that differ from the ones in this repo, please suggest modifications or just upload your files here.

**Comment by dimka4996** [comment]
> I would rather not be contacted privately about this. If you have settings that differ from the ones in this repo, please suggest modifications or just upload your files here.

I want to team up and try create a layout for AppleALC

**Comment by postkevone** [comment]
I am sorry, but since I do not own this laptop anymore I cannot make tests on it.

**Comment by postkevone** [comment]
Closing this issue as the problem seems to have been solved.
