### ISSUE TITLE
Wake by opening the lid twice

### ISSUE THREAD

**Issue by KatLantyss** [postkevone/razer-blade-stealth-13-oc#6]
Have you solved this problem yet?

**Comment by postkevone** [comment]
I do not own this laptop anymore so I cannot make any test, but someone has reached out to me with this fix:

[SSDT-LID.zip](https://github.com/user-attachments/files/17690675/SSDT-LID.zip)

![SSDT-LID](https://github.com/user-attachments/assets/181a789c-bc76-4816-89fc-604fe091504c)

Let me know if this works for you.

**Comment by KatLantyss** [comment]
Good news, It works perfectly!

**Comment by KatLantyss** [comment]
Good news, It works perfectly!
